[book]
authors = ["Brandon Frohs"]
language = "en"
multilingual = false
src = "book"
title = "Oxiplate Documentation"

[rust]
edition = "2024"

[build]
build-dir = "book-output"

[output.html]
git-repository-url = "https://github.com/0b10011/oxiplate"
edit-url-template = "https://github.com/0b10011/oxiplate/edit/main/{path}"
site-url = "/oxiplate/"

[output.html.playground]
runnable = false

[output.html.redirect]
"/writs.html" = "./templates/writs/index.html"
"/statements/extends.html" = "../templates/statements/extends.html"
"/statements/if-else.html" = "../templates/statements/if-else.html"
"/statements/for.html" = "../templates/statements/for.html"
"/whitespace-control.html" = "./templates/whitespace-control.html"
"/expressions.html" = "./templates/expressions.html"

[preprocessor.codename]
