[workspace]
release = false

[[package]]
name = "oxiplate"
release = true
changelog_include = ["oxiplate-derive"]

[[package]]
name = "oxiplate-derive"
release = true
changelog_include = ["oxiplate-traits"]
