# The macro by itself (`oxiplate_derive`) doesn't support escaping.
# This is only for tests directed at the macro.
# The main library (`oxiplate`) supported and tests escaping.
# Libraries and binaries using Oxiplate 
# will usually rely on inferring the escaper from file extensions,
# but they may also specify their own fallback escaper,
# possibly even "raw" for plain text use cases.
fallback_escaper_group = "raw"

# The macro by itself doesn't support escaping,
# and due to feature unification,
# when `cargo test` is run on the workspace,
# the `oxiplate` feature is turned on
# resulting in inferrence happening.
infer_escaper_group_from_file_extension = false
