name: deploy-book

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"

jobs:
  get-toolchain:
    uses: ./.github/workflows/existing-toolchain.yml

  book-setup:
    needs: get-toolchain
    uses: ./.github/workflows/book-setup.yml
    with:
      # Should match value in `/rust-toolchain.toml`
      toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

  book-tests:
    needs: get-toolchain
    uses: ./.github/workflows/book-tests.yml
    with:
      toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

  deploy:
    needs: [get-toolchain, book-setup, book-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ needs.get-toolchain.outputs.toolchain }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Restore book setup cache
        uses: actions/cache/restore@94b89442628ad1d101e352b7ee38f30e1bef108e # v5
        with:
          path: ${{ needs.book-setup.outputs.cache-path }}
          key: ${{ needs.book-setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Build book
        run: just book-build

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: 'book/output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
